---
- hosts: webservers
  become: yes
  tasks:
  - name: Install multiple application
    apt:
     name: "{{item}}"
     state: present
    loop:
     - git
     - python
     - wget
     - python3
     - gnome-chess
     - rhythmbox
  