---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
 # - include_tasks: tags.yml

  - name: i want to copy file Master to node
    copy:
     src: staticfile
     dest: /home/ubuntu/mystaticfile

  - name: copy the Dynamic file
    template: 
      src: index.j2
      dest: /var/www/html/index.html

  - name: Remote File download
    get_url:
      url: https://www.java.com/en/download/JavaSetup8u371.exe
      dest: /home/ubuntu/JavaSetup8u371.exe
      force_basic_auth: yes 

  

