---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to copy file Master to node
    copy:
     src: staticfile
     dest: /home/ubuntu/mystaticfile


  - include_tasks: webservers.yml
  
