---
- name: Download the tomcat 
  get_url:
    url: https://repo.maven.apache.org/maven2/org/apache/tomcat/tomcat/10.0.23/tomcat-10.0.23.tar.gz
    dest: /home/ubuntu/tomcat-10.0.23.tar.gz
    force_basic_auth: yes    

- name: create a folder
  file:
    path: /opt/tomcat
    state: directory

#if you execute Linux command directly as a admin, we are provide IDEMPOTENTS (one time only)
- name: Extarct the tomcat tar file
  command:
    cmd: sudo tar xzvf /home/ubuntu/tomcat-10.0.23.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/NOTICE

