---
# tasks file for webrole
- name: i Want to install Web server
  apt:
    name: apache2
    state: present

- name: Install the tree
  apt: 
    name: tree
    state: present

- name: install wget
  apt:
    name: wget
    state: present

- include_tasks: java.yml
